# Generated by Django 3.2.6 on 2022-10-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0003_auto_20221029_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
